- libs/upd/components/src/lib/data-table-styles/data-table-styles.component.html
- libs/upd/components/src/lib/data-table-styles/data-table-styles.component.spec.ts
- libs/upd/components/src/lib/data-table-styles/data-table-styles.component.ts
- libs/upd/components/src/lib/data-table-styles/types.ts
- libs/upd/components/src/lib/data-table/data-table.component.html
- libs/upd/components/src/lib/data-table/data-table.component.ts
- libs/upd/components/src/lib/upd-components.module.ts
- libs/upd/views/pages/src/lib/pages-home/pages-home.component.html
- libs/upd/views/pages/src/lib/pages-home/pages-home.component.ts
Created a component for styling, takes config. Changed the column config in Pages Home as a demo. Added tooltip also.
> Data Table styling

- apps/api/src/overall/overall.module.ts
- apps/api/src/overall/overall.service.ts
- libs/types-common/src/lib/data.types.ts
- libs/upd/components/src/lib/data-card/data-card.component.html
- libs/upd/components/src/lib/data-card/data-card.component.ts
- libs/upd/components/src/lib/data-table/data-table.component.ts
- libs/upd/components/src/lib/date-selector/date-selector.component.html
- libs/upd/views/overview/src/lib/+state/overview/overview.facade.ts
- libs/upd/views/overview/src/lib/overview-calldrivers/overview-calldrivers.component.html
- libs/upd/views/overview/src/lib/overview-calldrivers/overview-calldrivers.component.ts
- libs/upd/views/overview/src/lib/overview-feedback/overview-feedback.component.html
- libs/upd/views/overview/src/lib/overview-feedback/overview-feedback.component.ts
- libs/upd/views/overview/src/lib/overview-search-analytics/overview-search-analytics.component.html
- libs/upd/views/overview/src/lib/overview-search-analytics/overview-search-analytics.component.ts
- libs/upd/views/overview/src/lib/overview-summary/overview-summary.component.html
- libs/upd/views/overview/src/lib/overview-summary/overview-summary.component.ts
- libs/upd/views/overview/src/lib/overview-ux-tests/overview-ux-tests.component.html
- libs/upd/views/overview/src/lib/overview-ux-tests/overview-ux-tests.component.ts
- libs/upd/views/overview/src/lib/overview-webtraffic/overview-webtraffic.component.html
- libs/upd/views/overview/src/lib/overview-webtraffic/overview-webtraffic.component.ts
- libs/upd/views/pages/src/lib/pages-home/pages-home.component.ts
Updated Data Card component, Updated the HTML for the views under Overview, Fetched and Piped GSC data, DYF data, Top 10 Pages (takes 30 seconds to load Overview at the moment), beware.
> Overview section updates

- libs/upd/views/projects/src/lib/project-details/+state/projects-details.facade.ts
Fixes CCB placing Validation before Baseline
> Sorting array by most series first

- apps/api/src/overall/overall.service.ts
- libs/external-data/src/lib/adobe-analytics/queries.ts
- libs/external-data/src/lib/adobe-analytics/querybuilder.ts
- libs/types-common/src/lib/data.types.ts
- libs/upd/views/overview/src/lib/+state/overview/overview.facade.ts
- libs/upd/views/overview/src/lib/overview-feedback/overview-feedback.component.html
- libs/upd/views/overview/src/lib/overview-feedback/overview-feedback.component.ts
- libs/upd/views/pages/src/lib/pages-details/+state/pages-details.facade.ts
- libs/upd/views/pages/src/lib/pages-details/pages-details-summary/pages-details-summary.component.html
- libs/upd/views/pages/src/lib/pages-details/pages-details-summary/pages-details-summary.component.ts
- nx.json
- Missing Page Title and Page ID in DB; can't link them (have as external link for now)
> Updated Feedback data - Overview > Feedback

- apps/api/src/pages/pages.service.ts
- apps/api/src/tasks/tasks.service.ts
- libs/types-common/src/lib/data.types.ts
- libs/upd/views/tasks/src/lib/task-details/+state/tasks-details.reducer.ts
- Added Projects in Pages and Tasks for ease of implementation of the Project Names in Header
> Added Projects in Pages and Tasks

- apps/upd/src/app/components/header/header.component.html
- apps/upd/src/app/components/sidebar/sidebar.component.html
- libs/upd/components/src/lib/alert/alert.component.html
- libs/upd/components/src/lib/card/card.component.ts
- libs/upd/components/src/lib/date-selector/date-selector-dropdown.component.ts
- libs/upd/views/overview/src/lib/overview-calldrivers/overview-calldrivers.component.html
- libs/upd/views/pages/src/lib/pages-details/pages-details.component.html
- libs/upd/views/pages/src/lib/pages-home/pages-home.component.html
- libs/upd/views/projects/src/lib/project-details/project-details-calldrivers/project-details-calldrivers.component.html
- libs/upd/views/tasks/src/lib/task-details/task-details-calldrivers/task-details-calldrivers.component.html
Accessibility updates. Added tabindex="0" to allow users to use the tab key on the element. Also added aria-hidden="true" to hide the material icon name.
> Accessibility updates

- libs/upd/views/overview/src/lib/+state/overview/overview.selectors.spec.ts
Use mock store for ngrx overview selector testing
> ngrx selector automated testing update

- libs/upd/views/overview/src/lib/overview-calldrivers/overview-calldrivers.component.html
- libs/upd/views/overview/src/lib/overview-calldrivers/overview-calldrivers.component.ts
Updated the call volume data card on overview->calldrivers.
> Updated call volume data card

- libs/upd/views/overview/src/lib/+state/overview/overview.facade.ts
- libs/upd/views/overview/src/lib/overview-summary/overview-summary.component.ts
Added additional column for comparing period dates in the Visits compared to Call volume data table on Overview->Summary page. For weekly date range, changed format to full date (Day of week, Date).
> Added comparing period dates column

- libs/upd/views/overview/src/lib/+state/overview/overview.facade.ts
> Fix the range names to display the correct date/value

- apps/api/src/overall/overall.service.ts
- libs/types-common/src/lib/data.types.ts
- libs/upd/views/overview/src/lib/+state/overview/overview.facade.ts
- libs/upd/views/overview/src/lib/overview-search-analytics/overview-search-analytics.component.ts
- Updated the api to get the sat start date from db
- Using that for the front end title so it's always up to date
> [SAT frontend / overall api]

- libs/upd/views/projects/src/lib/project-details/project-details-summary/project-details-summary.component.html
- libs/upd/views/projects/src/lib/project-details/project-details-summary/project-details-summary.component.ts
Added the data cards from the old project details page to the project summary page. Added the project description, members list, and timeline data cards. Added dummy data into these data cards by hardcoding variables.
> Added data cards from old project details page to project summary page

- apps/api/src/tasks/tasks.controller.ts
- apps/api/src/tasks/tasks.service.ts
- apps/db-cli/src/app/scripts/scratchpad.ts
- libs/types-common/src/lib/data.types.ts
- libs/upd/views/tasks/src/lib/tasks-home/+state/tasks-home.effects.ts
- libs/upd/views/tasks/src/lib/tasks-home/+state/tasks-home.facade.ts
- libs/upd/views/tasks/src/lib/tasks-home/tasks-home.component.html
- libs/upd/views/tasks/src/lib/tasks-home/tasks-home.component.ts
Fixed the total visits and total calls data cards. Also added the percent change for these data cards.
> Fixed the total visits and total calls data cards

- libs/db-update/src/lib/airtable/feedback.service.ts
> Fix Feedback error

- libs/upd/views/projects/src/lib/project-details/+state/projects-details.facade.ts
- libs/upd/views/projects/src/lib/project-details/+state/projects-details.reducer.ts
- libs/upd/views/projects/src/lib/project-details/+state/projects-details.selectors.ts
- libs/upd/views/projects/src/lib/project-details/project-details.component.html
- libs/upd/views/projects/src/lib/project-details/project-details.component.ts
Added the loading spinner on the Projects->Details page.
> Added loading spinner on Projects->Details page

- libs/upd/views/pages/src/lib/pages-home/pages-home.component.html
- libs/upd/views/pages/src/lib/pages-home/pages-home.component.ts
Changed the Pages title from text to link
Inhibited the Pages title tooltip
> Change Pages title from text to link and inhibit Pages title tooltip

- libs/db-update/src/lib/airtable/annotations.service.ts
- libs/db-update/src/lib/airtable/calldrivers.service.ts
- libs/db-update/src/lib/db-update.module.ts
- libs/db-update/src/lib/db-update.service.ts
- libs/db-update/src/lib/overall-metrics/overall-metrics.service.ts
- libs/db/src/lib/db.module.ts
- libs/db/src/lib/db.schemas.ts
- libs/db/src/lib/db.service.ts
- libs/db/src/lib/schemas/annotations.schema.ts
- libs/external-data/src/lib/airtable/index.ts
Added event annotations to the db-update service. Also replaced withRetry with the Retry decorator.
> Added event annotations to the db-update service

- apps/api/src/overall/overall.service.ts
- libs/types-common/src/lib/data.types.ts
- libs/upd/components/src/lib/apex-bar-line/apex-bar-line.component.html
- libs/upd/components/src/lib/apex-bar-line/apex-bar-line.component.ts
- libs/upd/components/src/lib/apex-bar-line/apex.store.ts
- libs/upd/components/src/lib/apex-bar/apex-bar.component.html
- libs/upd/components/src/lib/apex-bar/apex-bar.component.ts
- libs/upd/components/src/lib/apex-bar/apex.store.ts
- libs/upd/i18n/src/lib/translations/en-CA.json
- libs/upd/i18n/src/lib/translations/fr-CA.json
- libs/upd/views/overview/src/lib/+state/overview/overview.facade.ts
- libs/upd/views/overview/src/lib/+state/overview/overview.selectors.ts
- libs/upd/views/overview/src/lib/overview-summary/overview-summary.component.html
- libs/upd/views/overview/src/lib/overview-summary/overview-summary.component.ts
- libs/upd/views/overview/src/lib/overview-webtraffic/overview-webtraffic.component.html
- libs/upd/views/overview/src/lib/overview-webtraffic/overview-webtraffic.component.ts
> Added event annotations

- libs/upd/views/projects/src/lib/project-details/+state/projects-details.facade.ts
Calculate Change by first rounding Baseline and Validation
> Task Success By UX Test

- libs/upd/views/projects/src/lib/project-details/project-details-summary/project-details-summary.component.html
- libs/upd/views/projects/src/lib/project-details/project-details-ux-tests/project-details-ux-tests.component.html
- libs/upd/views/tasks/src/lib/task-details/task-details-ux-tests/task-details-ux-tests.component.ts
Change Participant tasks to Related tasks in Project details summary and Project details UX Tests
> Change title names

- libs/types-common/src/lib/data.types.ts
- libs/upd/views/projects/src/lib/project-details/+state/projects-details.facade.ts
- libs/upd/views/projects/src/lib/project-details/project-details-feedback/project-details-feedback.component.html
- libs/upd/views/projects/src/lib/project-details/project-details-feedback/project-details-feedback.component.ts
- libs/upd/views/tasks/src/lib/task-details/+state/tasks-details.facade.ts
- libs/upd/views/tasks/src/lib/task-details/task-details-feedback/task-details-feedback.component.html
- libs/upd/views/tasks/src/lib/task-details/task-details-feedback/task-details-feedback.component.ts
Introducing total comments for projects and tasks page feedback
> Introduce total comments

- libs/upd/views/overview/src/lib/+state/overview/overview.facade.ts
- libs/upd/views/overview/src/lib/overview-calldrivers/overview-calldrivers.component.html
- libs/upd/views/overview/src/lib/overview-calldrivers/overview-calldrivers.component.ts
Added filter to the enquiry line column in the call drivers table.
> Added filter to enquiry line column

- libs/upd/i18n/src/lib/translations/en-CA.json
- libs/upd/i18n/src/lib/translations/fr-CA.json
- libs/upd/views/overview/src/lib/+state/overview/overview.facade.ts
- libs/upd/views/overview/src/lib/overview-calldrivers/overview-calldrivers.component.html
- libs/upd/views/overview/src/lib/overview-calldrivers/overview-calldrivers.component.ts
- libs/upd/views/overview/src/lib/overview-feedback/overview-feedback.component.ts
- libs/upd/views/overview/src/lib/overview-search-analytics/overview-search-analytics.component.ts
- libs/upd/views/overview/src/lib/overview-webtraffic/overview-webtraffic.component.ts
- libs/upd/views/pages/src/lib/pages-details/+state/pages-details.facade.ts
- libs/upd/views/pages/src/lib/pages-details/pages-details-search-analytics/pages-details-search-analytics.component.ts
- libs/upd/views/pages/src/lib/pages-details/pages-details-summary/pages-details-summary.component.ts
- libs/upd/views/pages/src/lib/pages-details/pages-details-webtraffic/pages-details-webtraffic.component.ts
- libs/upd/views/projects/src/lib/project-details/+state/projects-details.facade.ts
- libs/upd/views/projects/src/lib/project-details/project-details-calldrivers/project-details-calldrivers.component.html
- libs/upd/views/projects/src/lib/project-details/project-details-calldrivers/project-details-calldrivers.component.ts
- libs/upd/views/projects/src/lib/project-details/project-details-feedback/project-details-feedback.component.ts
- libs/upd/views/projects/src/lib/project-details/project-details-search-analytics/project-details-search-analytics.component.ts
- libs/upd/views/projects/src/lib/project-details/project-details-webtraffic/project-details-webtraffic.component.ts
- libs/upd/views/tasks/src/lib/task-details/+state/tasks-details.facade.ts
- libs/upd/views/tasks/src/lib/task-details/task-details-calldrivers/task-details-calldrivers.component.html
- libs/upd/views/tasks/src/lib/task-details/task-details-calldrivers/task-details-calldrivers.component.ts
- libs/upd/views/tasks/src/lib/task-details/task-details-feedback/task-details-feedback.component.ts
- libs/upd/views/tasks/src/lib/task-details/task-details-summary/task-details-summary.component.ts
- libs/upd/views/tasks/src/lib/task-details/task-details-webtraffic/task-details-webtraffic.component.ts
Changed "Comparison" to "Change" and "Inquiry" to "Enquiry".
> Update "Comparison" and "Inquiry"

- apps/api/src/projects/projects.service.ts
- apps/api/src/reports/reports.service.ts
- apps/upd/src/styles.scss
- libs/types-common/src/lib/data.types.ts
- libs/upd/components/src/lib/data-table-exports/data-table-exports.component.ts
- libs/upd/components/src/lib/project-status-label/project-status-label.component.ts
- libs/upd/i18n/src/lib/translations/en-CA.json
- libs/upd/i18n/src/lib/translations/fr-CA.json
Changed "Being monitored" status to "Monitoring".
> Update "Being monitored" status

- apps/db-cli/src/app/scripts/db.ts
- Added intervals to get either full, weekly, monthly, quarterly granularity
- cleaned up code
> Updated db.ts for more ease of use
